# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y universal-ctags || sudo apt-get install -y exuberant-ctags || sudo apt-get install -y ctags; fi
  # If we want the Universal Ctags master. No tagged releases yet.
  # - if [ $TRAVIS_OS_NAME = osx ]; then brew tap universal-ctags/universal-ctags && brew install --HEAD universal-ctags; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install ctags; fi
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
